apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircd
  labels:
    app: ircd
spec:
  replicas: 1 # Will increase in prod
  selector:
    matchLabels:
      app: ircd
  template:
    metadata:
      labels:
        app: ircd
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ircd
        # The tag will be dynamically substituted by GitHub Actions using sed before apply
        image: ghcr.io/eran-meir/irc/ircd:0b963ea2a437bbf4fcded2c40ee3e6b51f2018eb
        imagePullPolicy: Always
        ports:
        - containerPort: 6667
          name: irc
        - containerPort: 9090
          name: metrics
        env:
        - name: VALKEY_URL
          value: "valkey:6379"
