apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ircd-podmonitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ircd
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 5s
