apiVersion: v1
kind: Service
metadata:
  name: ircd
spec:
  # In k3s, LoadBalancer automatically creates a host port mapping on the node
  type: LoadBalancer 
  selector:
    app: ircd
  ports:
    - protocol: TCP
      port: 6667
      targetPort: 6667
      name: irc
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: metrics-ws
