apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 61.3.2
    chart: kube-prometheus-stack
    helm:
      values: |
        alertmanager:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false
        grafana:
          adminExistingSecret: "grafana-admin-secret"
          sidecar:
            datasources:
              enabled: true
              defaultDatasourceEnabled: true
              defaultDatasourceUid: "prometheus"
            dashboards:
              enabled: true
              searchNamespace: ALL
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki
              url: http://loki-stack.monitoring.svc.cluster.local:3100
              access: proxy
          grafana.ini:
            server:
              root_url: "%(protocol)s://%(domain)s/monitoring-test/"
              serve_from_sub_path: true
          service:
            type: ClusterIP
            port: 80
            targetPort: 3000
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - ""
            path: "/monitoring-test"
            paths:
              - "/monitoring-test"
              - "/monitoring-prod"
              - "/monitoring"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        prometheus:
          enabled: true
          prometheusSpec:
            scrapeInterval: 15s
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            retention: 2d
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 300m
                memory: 768Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
