apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 61.3.2
    chart: kube-prometheus-stack
    helm:
      values: |
        alertmanager:
          enabled: false
        grafana:
          adminExistingSecret: "grafana-admin-secret"
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki
              url: http://loki-stack.monitoring.svc.cluster.local:3100
              access: proxy
          service:
            type: ClusterIP
            port: 3000
            targetPort: 3000
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - ""
            tls:
              - secretName: grafana-tls
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 2GB
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1024Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
